server:
  port: 8010

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/audio?useSSL=false
    username: root
    password: root
  redis:
    host: 127.0.0.1

security:
  oauth2:
    resource:
      jwt:
        key-value: springcloud123



management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level.org.springframework.security: DEBUG
