server:
  port: 8061


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888//uaa/user
      prefer-token-info: false


management:
  endpoints:
    web:
      exposure:
        include: "*"
