server:
  port: 8061

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

security:
  oauth2:
    resource:
      jwt:
        key-value: springcloud123



management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level.org.springframework.security: DEBUG
