server:
  port: 8051

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true
      datasource:
        ds1:
          file:
            file: "classpath: flowrule.json"
            data-type: json
            rule-type: flow
feign:
  sentinel:
    enabled: true

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8888//uaa/user
      prefer-token-info: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging.level.org.springframework.security: DEBUG
